### ISSUE TITLE
Question using plugins

### ISSUE THREAD

**Issue by Cally99** [hex-digital/nuxtpress#18]
Hi there,

I've a question around plugins. 
Say I want to use ninja forms. Are forms and plugins supported?
I've tried to create a form and after publish I cannot see either on front or backend.

Thanks

**Comment by Jamiewarb** [comment]
The backend is just Wordpress, so if you can't see it there I'm not sure it's been set up correctly?

As for the front end, you'd need to see if the plug-in has REST API support. If it does, you can follow that to get the data on the front end. If it doesn't, you'll need to do it yourself.

**Comment by Cally99** [comment]
I was using the northosts repo and encountered a few issues so I've decided to use yours. Ninja forms didn't work and I'm going to have a play around with this repo instead as I think it's a bit smoother and has a few extra bells and whistles. Do you use this boilerplate for regular projects?
